# # -------------------------
# # --------- Deigo ---------
# # -------------------------
version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  database:
    image: postgres:alpine
    container_name: transcendence_db
    hostname: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: transcendence_redis
    networks:
      - app-network

  backend:
    build:
      context: ./cabraping.be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=database
      - DB_PORT=5432
    networks:
      - app-network

  nginx:
    build:
      context: ./cabraping.fe
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - redis
      - database
    networks:
      - app-network

volumes:
  postgres_data:
