# https://docs.docker.com/engine/reference/commandline/compose_up
version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: cabraping-redis
    hostname: database
    restart: always
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    container_name: transcendence_db
    hostname: database
    restart: always
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - 5433:5432
      # - 5432:5432
    env_file:
      - .env

volumes:
  redis_data:
  postgres_data: